spring:
  profiles:
    active: dev

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/inventory_management
    username: root
  jpa:
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: release
  datasource:
    password: password
    url: url
    username: username
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
---
