spring:
  profiles:
    active: dev

server:
  port: 8080
#  servlet:
#    context-path: /api/v1

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/spring_task
    username: root
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        check_nullability: true
        #        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: release
  datasource:
    password: password
    url: sqlServerConnString
    username: sa
  jpa:
    hibernate:
#      globally_quoted_identifiers: true
      ddl-auto: update
      format_sql: true
    show-sql: true
---
